name: Build-OpenWrt CI

on:
  schedule:
    - cron: 0 8 * * 5
#  push:
#    branches:
#      - openwrt-ci

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        ref: master
    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php
    - name: Update feeds
      run: |
        ./scripts/feeds update -a 
        ./scripts/feeds install -a
    - name: Start Build
      run: | 
        make defconfig
        let make_process=$(nproc)+1
        make -j${make_process}
    - name: Upload Packages
      uses: actions/upload-artifact@master
      with:
        name: Packages
        path: bin/packages/
    - name: Upload Firmwares
      uses: actions/upload-artifact@master
      with:
        name: Firmwares
        path: bin/targets/
